### ISSUE TITLE
Telemetry is too verbose

### ISSUE THREAD

**Issue by fcdenos** [ystia/yorc#354] opened 2019-03-27 16:54 UTC
# Bug Report

## Description

When enabling telemetry we get logs like this : 
yorc_http_GET_deployments_ACD_ACCOMPAGNEMENT_PROJET_DEVOPS_SGCloudCompute_tests_yorc_machine_unique_nodes_SGCloudComputemacornac_instances_0_attributes_ports yorc_http_GET_deployments_ACD_ACCOMPAGNEMENT_PROJET_DEVOPS_SGCloudCompute_tests_yorc_machine_unique_nodes_SGCloudComputemacornac_instances_0_attributes_ports
yorc_http_GET_deployments_ACD_ACCOMPAGNEMENT_PROJET_DEVOPS_SGCloudCompute_tests_yorc_machine_unique_nodes_SGCloudComputemacornac_instances_0_attributes_ports summary
yorc_http_GET_deployments_ACD_ACCOMPAGNEMENT_PROJET_DEVOPS_SGCloudCompute_tests_yorc_machine_unique_nodes_SGCloudComputemacornac_instances_0_attributes_ports{quantile="0.5"} NaN
yorc_http_GET_deployments_ACD_ACCOMPAGNEMENT_PROJET_DEVOPS_SGCloudCompute_tests_yorc_machine_unique_nodes_SGCloudComputemacornac_instances_0_attributes_ports{quantile="0.9"} NaN
yorc_http_GET_deployments_ACD_ACCOMPAGNEMENT_PROJET_DEVOPS_SGCloudCompute_tests_yorc_machine_unique_nodes_SGCloudComputemacornac_instances_0_attributes_ports{quantile="0.99"} NaN
yorc_http_GET_deployments_ACD_ACCOMPAGNEMENT_PROJET_DEVOPS_SGCloudCompute_tests_yorc_machine_unique_nodes_SGCloudComputemacornac_instances_0_attributes_ports_sum 554.2170562744141
yorc_http_GET_deployments_ACD_ACCOMPAGNEMENT_PROJET_DEVOPS_SGCloudCompute_tests_yorc_machine_unique_nodes_SGCloudComputemacornac_instances_0_attributes_ports_count 2

The problem is that we get a check for each attribute/property of every node of every deployment ... Which does not seem very useful and can be very (time? / disk) consuming in production platforms (1000s of deployments ... )
Would it be possible to stop checking for every attribute/prop ?

## Steps to reproduce the issue

1. Step1
2. Step2 ...

## Priority

High / Medium / Low

* High = We should stop anything we are doing and do this. If you're writing this calmly, you should probably choose another option. If it's really that urgent, please make sure we read this.
* Medium = It's important that we do this within a few days.
* Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).

**Comment by loicalbertin** [comment] 2019-04-04 12:13
Hi @fcdenos 

What you see is the telemetry on the REST API we need this to mesure response time.
That said, regarding checking attributes this is done by #313 attributes changes are now pushed using the events API instead of being regularly pulled.

Just to be sure, to get your point, are you seeing this in logs or in a metering system?

**Comment by fcdenos** [comment] 2019-04-05 11:35
Hi @loicalbertin 

I understand this measures REST API Response time, however I don't understand why you would want to measure the reponse time for a particular attribute, then the response time for another attribute, then the response time for every attribute ... 
Why not measure it for only one attribute ? Aren't all attributes the same ? (from a performance point of view) 

We are seeing thins in the logs

**Comment by loicalbertin** [comment] 2019-04-09 09:36
In fact we are measuring response time on REST API paths generically, this is not specific to attributes. The fact is that we have a specific REST path for each attribute.
We plan to refactor our metering system by making use of `tags` that Prometheus can leverage, unfortunately I think that for statsd/statsite it will result in similar long key paths...  

That said those metrics should not appear in Yorc's logs. I will check it.

**Comment by loicalbertin** [comment] 2019-04-09 12:22
Hi @fcdenos ,

I can't reproduce telemetry logs appearing in Yorc's logs.
Could you please send your Yorc's config?

**Comment by loicalbertin** [comment] 2019-05-28 08:56
Closing this as we can't reproduce it.
Please feel free to reopen it with material for a reproduction if you are still facing this issue.

**Closed by loicalbertin** 2019-05-28 08:56 UTC
Labels: bug
